version: '3'

services:
  # nomad:
  #   image: multani/nomad:1.1.6
  #   command: agent -dev
  #   privileged: true
  #   environment:
  #     NOMAD_DATA_DIR: /tmp/nomad/data
  #     NOMAD_LOCAL_CONFIG: |
  #       datacenter = "${REGION:-test}"
  #       region     = "${DATACENTER:-test-dc1}"

  #       data_dir = "/nomad/data/"

  #       bind_addr = "0.0.0.0"
  #       advertise {
  #         http = "{{ GetPrivateIP }}:4646"
  #         rpc  = "{{ GetPrivateIP }}:4647"
  #         serf = "{{ GetPrivateIP }}:4648"
  #       }
  #       client {
  #         meta {
  #           nomad_uid = "998"
  #         }
  #       }
  #   ports:
  #     - 4646:4646
  #   volumes:
  #     - /tmp/nomad/data:/tmp/nomad/data
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #     - /tmp:/tmp

  rundeck:
    image: rundeck/rundeck:3.4.2
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
      RUNDECK_SERVER_FORWARDED: 'false'
      NOMAD_ADDR: http://nomad.service.test.consul:4646
      NOMAD_REGION: global
    volumes:
      - ./data:/home/rundeck/server/data
      - ./build/nomad-dispatch-plugin.zip:/home/rundeck/libext/nomad-dispatch-plugin.zip